spring:
  application:
    name: credit-system
  datasource:
    url: jdbc:h2:mem:creditdb
    username: test
    password: test
    driver-class-name: org.h2.Driver
    hikari:
      pool-name: H2-HikariPool
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 200000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      initialization-fail-timeout: 1
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


redisson:
  config: |
    singleServerConfig:
      address: "redis://localhost:6379"
      connectionMinimumIdleSize: 5
      connectionPoolSize: 10
      idleConnectionTimeout: 10000
      connectTimeout: 5000
      timeout: 3000

loan:
  max-installment:
    payment: 3

application:
  security:
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 86400000
