version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    container_name: banka_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    command: redis-server --save 60 1 --loglevel warning

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin       # İsteğe bağlı kullanıcı adı
      - HTTP_PASSWORD=admin   # İsteğe bağlı şifre
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
  redisinsight_data: